name: Code Check
on:
  push:
    branches: main
  pull_request:

env:
  FLUTTER_TEST_REPORT: ${{github.workspace}}/flutter-test-report.json
  PATTERN_CHECKER: ${{github.workspace}}/scripts/pattern_checker.sh

jobs:
  # Change detection
  setup:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      flutter-file-changed: ${{ steps.filter.outputs.flutter-file-changed }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            flutter-file-changed:
              - '**.dart'
              - 'pubspec.yaml'
              - 'pubspec.lock'

  # Static code analysis
  analysis:
    needs: setup
    if: ${{ needs.setup.outputs.flutter-file-changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: ./.github/actions/setup_flutter

      - name: Format
        run: dart format . -o none --set-exit-if-changed

      - name: Analyze
        run: dart analyze

      - name: Disallowed patterns check
        run: bash ${{ env.PATTERN_CHECKER }} "*.dart" "--" "debugPrint"

  # Unit testing
  testing:
    needs: setup
    if: ${{ needs.setup.outputs.flutter-file-changed == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: ./.github/actions/setup_flutter

      - name: Run unit tests
        run: flutter test --file-reporter="json:${{ env.FLUTTER_TEST_REPORT }}"

      - name: Write test report
        uses: dorny/test-reporter@v1
        # PRs from forks have no write permissions.
        if: github.event.pull_request.head.repo.fork == false && (success() || failure())
        with:
          name: Test Report
          path: ${{ env.FLUTTER_TEST_REPORT }}
          reporter: flutter-json

  # Final results (Used for status checks)
  code-check:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [analysis, testing]
    steps:
      # Fails if any of the previous jobs failed.
      - run: exit 1
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
          }}
